name: data_analysis
channels:
    - defaults
dependencies:
    - python=3.8
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - scipy
    - joblib
    - scikit-learn
    - requests
    - beautifulsoup4
    - jupyterlab
